/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.graphic_interface;

/**
 *
 * @author Alberto
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        getRootPane().setDefaultButton(AcceptButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContainer = new javax.swing.JPanel();
        MainMenuTITLE = new javax.swing.JPanel();
        MainMenuLabel = new javax.swing.JLabel();
        SelectOpLabel = new javax.swing.JLabel();
        OptionsMainMenu = new javax.swing.JComboBox<>();
        AcceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContainer.setBackground(new java.awt.Color(153, 255, 255));
        PanelContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainMenuTITLE.setBackground(new java.awt.Color(0, 204, 204));

        MainMenuLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        MainMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainMenuLabel.setText("--MENU PRINCIPAL--");

        javax.swing.GroupLayout MainMenuTITLELayout = new javax.swing.GroupLayout(MainMenuTITLE);
        MainMenuTITLE.setLayout(MainMenuTITLELayout);
        MainMenuTITLELayout.setHorizontalGroup(
            MainMenuTITLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuTITLELayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(MainMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        MainMenuTITLELayout.setVerticalGroup(
            MainMenuTITLELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuTITLELayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(MainMenuLabel)
                .addGap(19, 19, 19))
        );

        PanelContainer.add(MainMenuTITLE, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 70));

        SelectOpLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        SelectOpLabel.setForeground(new java.awt.Color(0, 0, 0));
        SelectOpLabel.setText("Seleccione una opción");
        PanelContainer.add(SelectOpLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, -1, -1));

        OptionsMainMenu.setBackground(new java.awt.Color(255, 255, 255));
        OptionsMainMenu.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        OptionsMainMenu.setForeground(new java.awt.Color(0, 0, 0));
        OptionsMainMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presentacion", "Programa 1", "Programa 2", "Programa 3", "Salir" }));
        OptionsMainMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptionsMainMenuActionPerformed(evt);
            }
        });
        PanelContainer.add(OptionsMainMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 170, 40));

        AcceptButton.setBackground(new java.awt.Color(129, 155, 207));
        AcceptButton.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        AcceptButton.setForeground(new java.awt.Color(255, 255, 255));
        AcceptButton.setText("Aceptar");
        AcceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcceptButtonActionPerformed(evt);
            }
        });
        PanelContainer.add(AcceptButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 570, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcceptButtonActionPerformed
            // Obtiene la opción seleccionada en el menú principal
            String select = OptionsMainMenu.getSelectedItem().toString();

            // Verifica si la opción seleccionada es "Presentation"
            if(select.equals("Presentacion")){
            // Abre la ventana de presentación y cierra la actual
                Presentation presentationPage = new Presentation();
                presentationPage.setVisible(true);
                presentationPage.setLocationRelativeTo(null);
                this.dispose(); 

            // Verifica si la opción seleccionada es "Program 1"
            } else if(select.equals("Programa 1")){
                // Abre la ventana del Programa 1
                Program1 program1 = new Program1();
                program1.setVisible(true);
                program1.setLocationRelativeTo(null);
                this.dispose();

            // Verifica si la opción seleccionada es "Program 2"
            } else if(select.equals("Programa 2")){
                // Abre la ventana del Programa 2

            // Verifica si la opción seleccionada es "Program 3"
            } else if(select.equals("Programa 3")){
               // Abre la ventana del Programa 3


            // Verifica si la opción seleccionada es "Exit"
            } else if(select.equals("Salir")){
                // Cierra la aplicación
                System.exit(0);
            }

    }//GEN-LAST:event_AcceptButtonActionPerformed

    private void OptionsMainMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptionsMainMenuActionPerformed

    }//GEN-LAST:event_OptionsMainMenuActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcceptButton;
    private javax.swing.JLabel MainMenuLabel;
    private javax.swing.JPanel MainMenuTITLE;
    private javax.swing.JComboBox<String> OptionsMainMenu;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JLabel SelectOpLabel;
    // End of variables declaration//GEN-END:variables
}
