/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.graphic_interface;

/**
 *
 * @author Alberto
 */
public class Presentation extends javax.swing.JFrame {

  /**
     * Creates new form Presentation
     */
  public Presentation() {
    initComponents();
  }

  /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        UTP_Logo = new javax.swing.JLabel();
        FISC_Logo = new javax.swing.JLabel();
        SOFT_DEVLabel = new javax.swing.JLabel();
        FISCLabel = new javax.swing.JLabel();
        ProjectTtitle = new javax.swing.JLabel();
        UTPLabel = new javax.swing.JLabel();
        MemberJose = new javax.swing.JLabel();
        Memebers = new javax.swing.JLabel();
        MemberAlberto = new javax.swing.JLabel();
        MemberJosue = new javax.swing.JLabel();
        MemberAlexa = new javax.swing.JLabel();
        MemberDaniel = new javax.swing.JLabel();
        MemberAnthony = new javax.swing.JLabel();
        Exit_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));

        UTP_Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alberto\\OneDrive\\Documentos\\LogoUTP2.jpg")); // NOI18N

        FISC_Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Alberto\\OneDrive\\Documentos\\FISC_logo.png")); // NOI18N

        SOFT_DEVLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        SOFT_DEVLabel.setForeground(new java.awt.Color(0, 0, 0));
        SOFT_DEVLabel.setText("LICIENCIATURA EN DESARROLLO Y GESTION DE SOFTWARE");

        FISCLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        FISCLabel.setForeground(new java.awt.Color(0, 0, 0));
        FISCLabel.setText("FACULTAD DE INGENIERÍA DE SISTEMAS COMPUTACIONALES");

        ProjectTtitle.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ProjectTtitle.setForeground(new java.awt.Color(0, 0, 0));
        ProjectTtitle.setText("PROYECTO #2");

        UTPLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        UTPLabel.setForeground(new java.awt.Color(0, 0, 0));
        UTPLabel.setText("UNIVERSIDAD TECNOLÓGICA DE PANAMÁ ");

        MemberJose.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        MemberJose.setForeground(new java.awt.Color(0, 0, 0));
        MemberJose.setText("Jose Carranza 2-769-562");

        Memebers.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        Memebers.setForeground(new java.awt.Color(0, 0, 0));
        Memebers.setText("INTEGRANTES:");

        MemberAlberto.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        MemberAlberto.setForeground(new java.awt.Color(0, 0, 0));
        MemberAlberto.setText("Alberto Carranza 2-769-563");

        MemberJosue.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        MemberJosue.setForeground(new java.awt.Color(0, 0, 0));
        MemberJosue.setText("Josue Flores 9-767-790");

        MemberAlexa.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        MemberAlexa.setForeground(new java.awt.Color(0, 0, 0));
        MemberAlexa.setText("Alexandra De Gracia 8-1026-180");

        MemberDaniel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        MemberDaniel.setForeground(new java.awt.Color(0, 0, 0));
        MemberDaniel.setText("Daniel Ubarte 8-1025-1817");

        MemberAnthony.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        MemberAnthony.setForeground(new java.awt.Color(0, 0, 0));
        MemberAnthony.setText("Anthony Perez 2-755-2432");

        Exit_Button.setBackground(new java.awt.Color(204, 204, 255));
        Exit_Button.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        Exit_Button.setForeground(new java.awt.Color(0, 0, 0));
        Exit_Button.setText("Salir");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BackgroundLayout = new javax.swing.GroupLayout(Background);
        Background.setLayout(BackgroundLayout);
        BackgroundLayout.setHorizontalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProjectTtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(335, 335, 335))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(FISC_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Memebers, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemberAnthony)
                    .addComponent(MemberDaniel)
                    .addComponent(MemberAlexa)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FISCLabel)
                            .addComponent(SOFT_DEVLabel))
                        .addGap(31, 31, 31)
                        .addComponent(UTP_Logo))
                    .addComponent(MemberJose, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MemberAlberto)
                    .addComponent(MemberJosue, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLayout.createSequentialGroup()
                    .addContainerGap(259, Short.MAX_VALUE)
                    .addComponent(UTPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(204, 204, 204)))
        );
        BackgroundLayout.setVerticalGroup(
            BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLayout.createSequentialGroup()
                .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(BackgroundLayout.createSequentialGroup()
                                .addComponent(FISCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SOFT_DEVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(UTP_Logo)))
                    .addGroup(BackgroundLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(FISC_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(ProjectTtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(Memebers, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberJose, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberAlberto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberJosue, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberAlexa, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberDaniel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MemberAnthony, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(21, 21, 21))
            .addGroup(BackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(BackgroundLayout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(UTPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
    MainMenu mainMenu = new MainMenu();
    mainMenu.setVisible(true);
    mainMenu.setLocationRelativeTo(null);
    this.dispose();

  }//GEN-LAST:event_Exit_ButtonActionPerformed

  /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JLabel FISCLabel;
    private javax.swing.JLabel FISC_Logo;
    private javax.swing.JLabel MemberAlberto;
    private javax.swing.JLabel MemberAlexa;
    private javax.swing.JLabel MemberAnthony;
    private javax.swing.JLabel MemberDaniel;
    private javax.swing.JLabel MemberJose;
    private javax.swing.JLabel MemberJosue;
    private javax.swing.JLabel Memebers;
    private javax.swing.JLabel ProjectTtitle;
    private javax.swing.JLabel SOFT_DEVLabel;
    private javax.swing.JLabel UTPLabel;
    private javax.swing.JLabel UTP_Logo;
    // End of variables declaration//GEN-END:variables
}
