/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.graphic_interface;

import com.example.calculations.CalculationsProgram2;
import com.example.validates.ValidatesProgram2;
import javax.swing.JOptionPane;

/**
 *
 * @author Alberto
 */
public class Program2 extends javax.swing.JFrame {
    CalculationsProgram2 calculationsprogram2 = new CalculationsProgram2();
    // Variable booleana para verificar si la matriz ya fue llenada
    private boolean isMatrixFilled = false;
    /**
     * Creates new form Program2
     */
    public Program2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelContainer = new javax.swing.JPanel();
        TtitlePanelContainer = new javax.swing.JPanel();
        ProgramTitle = new javax.swing.JLabel();
        LabelNumberOfSellers = new javax.swing.JLabel();
        LabelNumberOfMonths = new javax.swing.JLabel();
        numberOfSellers = new javax.swing.JTextField();
        numberOfMonths = new javax.swing.JTextField();
        ConfirmValuesBttn = new javax.swing.JButton();
        OperationsMenuLabel = new javax.swing.JLabel();
        OperationsMenu = new javax.swing.JComboBox<>();
        SelectOptionBttn = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ResetValuesBttn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelContainer.setBackground(new java.awt.Color(102, 165, 173));

        TtitlePanelContainer.setBackground(new java.awt.Color(110, 181, 190));

        ProgramTitle.setFont(new java.awt.Font("Tw Cen MT", 2, 30)); // NOI18N
        ProgramTitle.setForeground(new java.awt.Color(255, 255, 255));
        ProgramTitle.setText("-PROGRAMA 2-");

        javax.swing.GroupLayout TtitlePanelContainerLayout = new javax.swing.GroupLayout(TtitlePanelContainer);
        TtitlePanelContainer.setLayout(TtitlePanelContainerLayout);
        TtitlePanelContainerLayout.setHorizontalGroup(
            TtitlePanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TtitlePanelContainerLayout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(ProgramTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        TtitlePanelContainerLayout.setVerticalGroup(
            TtitlePanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TtitlePanelContainerLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(ProgramTitle)
                .addGap(20, 20, 20))
        );

        LabelNumberOfSellers.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LabelNumberOfSellers.setForeground(new java.awt.Color(255, 255, 255));
        LabelNumberOfSellers.setText("Ingrese la cantidad de vendedores:");

        LabelNumberOfMonths.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        LabelNumberOfMonths.setForeground(new java.awt.Color(255, 255, 255));
        LabelNumberOfMonths.setText("Ingrese la cantidad de meses:");

        numberOfSellers.setBackground(new java.awt.Color(181, 202, 224));
        numberOfSellers.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        numberOfSellers.setForeground(new java.awt.Color(0, 0, 0));
        numberOfSellers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfSellersActionPerformed(evt);
            }
        });

        numberOfMonths.setBackground(new java.awt.Color(181, 202, 224));
        numberOfMonths.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        numberOfMonths.setForeground(new java.awt.Color(0, 0, 0));
        numberOfMonths.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOfMonthsActionPerformed(evt);
            }
        });

        ConfirmValuesBttn.setBackground(new java.awt.Color(0, 153, 153));
        ConfirmValuesBttn.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ConfirmValuesBttn.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmValuesBttn.setText("Confirmar");
        ConfirmValuesBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmValuesBttnActionPerformed(evt);
            }
        });

        OperationsMenuLabel.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        OperationsMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        OperationsMenuLabel.setText("Menú de Operaciones: ");

        OperationsMenu.setBackground(new java.awt.Color(255, 255, 255));
        OperationsMenu.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        OperationsMenu.setForeground(new java.awt.Color(0, 0, 0));
        OperationsMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mostrar la matriz en formato tabular", "Imprimir el vector VtasPorVendedor", "Imprimir el vector PromPorVendedor", "Imprimir el vector VtasPorMes", "Imprimir el vector PromPorMes", "Totalizar las ventas del negocio" }));

        SelectOptionBttn.setBackground(new java.awt.Color(0, 153, 153));
        SelectOptionBttn.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        SelectOptionBttn.setForeground(new java.awt.Color(255, 255, 255));
        SelectOptionBttn.setText("Seleccionar");
        SelectOptionBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectOptionBttnActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(0, 153, 153));
        ExitButton.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Salir");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        ResetValuesBttn.setBackground(new java.awt.Color(0, 153, 153));
        ResetValuesBttn.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        ResetValuesBttn.setForeground(new java.awt.Color(255, 255, 255));
        ResetValuesBttn.setText("Reiniciar Valores");
        ResetValuesBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetValuesBttnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelContainerLayout = new javax.swing.GroupLayout(PanelContainer);
        PanelContainer.setLayout(PanelContainerLayout);
        PanelContainerLayout.setHorizontalGroup(
            PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TtitlePanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelContainerLayout.createSequentialGroup()
                .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelContainerLayout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(SelectOptionBttn))
                    .addGroup(PanelContainerLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelContainerLayout.createSequentialGroup()
                                .addComponent(ExitButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ResetValuesBttn))
                            .addComponent(ConfirmValuesBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelContainerLayout.createSequentialGroup()
                                .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelNumberOfSellers, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelNumberOfMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberOfMonths, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(numberOfSellers, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContainerLayout.createSequentialGroup()
                .addGap(0, 146, Short.MAX_VALUE)
                .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContainerLayout.createSequentialGroup()
                        .addComponent(OperationsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelContainerLayout.createSequentialGroup()
                        .addComponent(OperationsMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(194, 194, 194))))
        );
        PanelContainerLayout.setVerticalGroup(
            PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelContainerLayout.createSequentialGroup()
                .addComponent(TtitlePanelContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNumberOfSellers)
                    .addComponent(numberOfSellers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfMonths, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNumberOfMonths))
                .addGap(18, 18, 18)
                .addComponent(ConfirmValuesBttn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(OperationsMenuLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OperationsMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(SelectOptionBttn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(PanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(ResetValuesBttn))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
          //Al presionar el boton Salir, muestra el menu principal
        MainMenu mainMenu = new MainMenu();
        mainMenu.setVisible(true);
        mainMenu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void ConfirmValuesBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmValuesBttnActionPerformed
         // Verificar si la matriz ya ha sido llenada
            if (isMatrixFilled) {
                JOptionPane.showMessageDialog(
                    null,
                    "Los valores de la matriz ya han sido ingresados.",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE
                );
                return;
            }
        
        String strSellers, strMonths;
        strSellers = numberOfSellers.getText();
        strMonths = numberOfMonths.getText();
        
        if(ValidatesProgram2.validateEmptyValues(strSellers, strMonths)){
            numberOfSellers.setText("");
            numberOfMonths.setText("");
            numberOfSellers.requestFocus();
            return;
        }
        
        int NumberOfSellers, NumberOfMonths;
        try{
            NumberOfSellers = Integer.parseInt(strSellers);
            NumberOfMonths = Integer.parseInt(strMonths);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, 
                    "Los valores deben ser números enteros ", "Error", 0);
            numberOfSellers.setText("");
            numberOfMonths.setText("");
            numberOfSellers.requestFocus();
            return;
        }
        
        if(ValidatesProgram2.validatePositive(NumberOfSellers, NumberOfMonths)){
            numberOfSellers.setText("");
            numberOfMonths.setText("");
            numberOfSellers.requestFocus();
            return;
        }
        
         boolean matrixFilledSuccessfully = calculationsprogram2.fillMatrix(NumberOfSellers, NumberOfMonths); //este es llamado del metodo para llenar la matriz
        
        // Si la matriz fue llenada correctamente, actualizar el indicador y mostrar mensaje
            if (matrixFilledSuccessfully) {
                isMatrixFilled = true;
                JOptionPane.showMessageDialog(
                    null,
                    "Los valores han sido ingresados exitosamente.",
                    "Confirmación",
                    JOptionPane.INFORMATION_MESSAGE
                );
            }
        
    }//GEN-LAST:event_ConfirmValuesBttnActionPerformed

    private void numberOfSellersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfSellersActionPerformed
         numberOfMonths.requestFocus();
    }//GEN-LAST:event_numberOfSellersActionPerformed

    private void SelectOptionBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectOptionBttnActionPerformed
         // Obtener la opción seleccionada del JComboBox
        String selectedOption = OperationsMenu.getSelectedItem().toString(); 
            // Llamar al método correspondiente en CalculationsProgram2 según la opción seleccionada
            if (selectedOption.equals("Mostrar la matriz en formato tabular")) {
                calculationsprogram2.showSalesMatrix();
            } else if (selectedOption.equals("Imprimir el vector VtasPorVendedor")) {
                calculationsprogram2.showSalesPerSeller();
            } else if (selectedOption.equals("Imprimir el vector PromPorVendedor")) {
                calculationsprogram2.showAvgPerSeller();
            } else if (selectedOption.equals("Imprimir el vector VtasPorMes")) {
                calculationsprogram2.showSalesPerMonth();
            } else if (selectedOption.equals("Imprimir el vector PromPorMes")) {
                calculationsprogram2.showAvgPerMonth();
            } else if (selectedOption.equals("Totalizar las ventas del negocio")) {
                calculationsprogram2.totalizeSales();
            }
        
    }//GEN-LAST:event_SelectOptionBttnActionPerformed

    private void numberOfMonthsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOfMonthsActionPerformed
        ConfirmValuesBttnActionPerformed(evt);
    }//GEN-LAST:event_numberOfMonthsActionPerformed

    private void ResetValuesBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetValuesBttnActionPerformed
        numberOfSellers.setText("");
        numberOfMonths.setText("");
        numberOfSellers.requestFocus();
        isMatrixFilled = false;
    }//GEN-LAST:event_ResetValuesBttnActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfirmValuesBttn;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel LabelNumberOfMonths;
    private javax.swing.JLabel LabelNumberOfSellers;
    private javax.swing.JComboBox<String> OperationsMenu;
    private javax.swing.JLabel OperationsMenuLabel;
    private javax.swing.JPanel PanelContainer;
    private javax.swing.JLabel ProgramTitle;
    private javax.swing.JButton ResetValuesBttn;
    private javax.swing.JButton SelectOptionBttn;
    private javax.swing.JPanel TtitlePanelContainer;
    private javax.swing.JTextField numberOfMonths;
    private javax.swing.JTextField numberOfSellers;
    // End of variables declaration//GEN-END:variables
}
